apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-registry
  labels:
    app: docker-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-registry
  template:
    metadata:
      labels:
        app: docker-registry
  spec:
      volumes:
      - name: certs-vol
        hostPath:
          path: /certs
          type: Directory
      - name: registry-vol
        hostPath:
          path: /data/Docker-Registry
          type: Directory

  containers:
      - image: registry:2
        name: docker-registry
        imagePullPolicy: IfNotPresent
        env:
          - name: REGISTRY_STORAGE_DELETE_ENABLED
            value: true
          - name: REGISTRY_HTTP_TLS_CERTIFICATE
            value: "/certs/registry.crt"
          - name: REGISTRY_HTTP_TLS_KEY
            value: "/certs/registry.key"
            ports:
            - containerPort: 5000
        volumeMounts:
          - name: certs-vol
            mountPath: /certs
          - name: registry-vol
            mountPath: data/Docker-Registry