keycloak:
  service:
    type: NodePort
    nodePort: 30880
app-server:
  service:
    type: NodePort
    nodePort: 31080
  keycloak:
    authServerUrl: "http://localhost:30880/auth"
  ingress:
    enabled: true
    hosts:
    - paths:
        - path: /
          pathType: Prefix
 
minio-bundled:
  buckets: [{"name": "ldc", "policy": "none"}, {"name": "ldc-demo-data", "policy": "none"}, {"name": "spark-history", "policy": "none"}]
  accessKey: minioadmin
  secretKey: minioadmin
  persistence:
    enabled: true
    size: 5Gi
  service:
    type: NodePort
    nodePort: 30900
  consoleService:
    type: NodePort
    nodePort: 30901
mongodb:
  service:
    type: NodePort
    nodePort: 30017
  persistence:
    enabled: true
    volumeClaim:
      size: 5Gi
      accessModes:
        - ReadWriteOnce